version: '3'

services:
  my-airflow:
    image: learnairflow:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
  my-smtp:
    image: bytemark/smtp
    restart: always